# general settings
name: 037_NAFNet_Benchmark_Deraining_Cosine_GT256B8_600k
model_type: ImageRestorationModel
scale: 1
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: PairedImageDataset
    dataroot_gt: /data/yhliu/DATA/Derain/train/Rain13K/target
    dataroot_lq: /data/yhliu/DATA/Derain/train/Rain13K/input

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_flip: true
    use_rot: true
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 2
    gt_size: 256
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Test100
    type: PairedImageDataset
    dataroot_gt: /data/yhliu/DATA/Derain/test/Test100/target
    dataroot_lq: /data/yhliu/DATA/Derain/test/Test100/input
    io_backend:
      type: disk

# network structures
network_g:
  type: NAFNet
  width: 64
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 600000
  warmup_iter: 5000 # -1 for no warm up
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]       
    restart_weights: [1]
    eta_min: 0.00000001

  mixing_augs:
    mixup: false
    mixup_beta: 2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 2e-2
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 5e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 1
  padding_factor: 8
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 250
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
