# general settings
name: 042_HINet_Benchmark_Gaussian_sigma50_Cosine_GT256B8_600k
model_type: ImageRestorationModel
scale: 1
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: GaussianNoiseImageDataset
    sigma_type: constant
    sigma_range: 50
    in_ch: 3    ## RGB image
    dataroot_gt:  /data/zyli/datasets/DFWB/train_patch_512_96
    dataroot_lq: none

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_flip: true
    use_rot: true
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 2
    gt_size: 256
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: CBSD68
    type: GaussianNoiseImageDataset
    sigma_test: 50
    in_ch: 3  ## RGB image
    dataroot_gt: /data/zyli/datasets/Gaussian_test/CBSD68
    dataroot_lq: none
    io_backend:
      type: disk

# network structures
network_g:
  type: HINet
  wf: 64
  hin_position_left: 0
  hin_position_right: 4


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
# training settings
train:
  total_iter: 600000
  warmup_iter: 5000 # -1 for no warm up
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]       
    restart_weights: [1]
    eta_min: 0.00000001

  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 2e-2
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 5e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 1
  padding_factor: 16
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: False

# logging settings
logger:
  print_freq: 250
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
